---
key_name: pop-webapp
id: web-app-hellow
app_port: 80

image: ami-0a0d2dc2f521ddce6
instance_type: t2.micro
region: eu-west-1

aws_sg:
  - name: "poppulo-{{ id }}"
    description: "Security Group for {{ id }}"
    vpcid: vpc-1aa1bf7c
    rules:
      - proto: tcp
        ports: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        ports: "{{ app_port }}"
        cidr_ip: 0.0.0.0/0
