---
- name: Enable RHEL extras Repo
  shell: "yum-config-manager --enable rhui-REGION-rhel-server-extras"

- name: Install Docker on EC2 Instance
  package:
    name: docker
    state: present

- name: Enable and Start the docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Copy over built WAR file
  copy:
    src: ~/poppulo/ansible/roles/build/files/hello.war
    dest: ~/hello.war
    owner: ec2-user
    group: ec2-user
    mode: 0644
