---
- name: Enable RHEL extras Repo
  shell: "yum-config-manager --enable rhui-REGION-rhel-server-extras"

- name: Install Docker on EC2 Instance
  package:
    name: docker
    state: present

- name: Enable and Start the docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Copy over built WAR file
  copy:
    src: /home/ec2-user/poppulo/ansible/roles/build_app/files/hello.war
    dest: /home/ec2-user/hello.war
    owner: ec2-user
    group: ec2-user
    mode: 0644

- name: Copy Dockerfile to server
  copy:
    src: /home/ec2-user/poppulo/ansible/roles/install_app/files/Dockerfile
    dest: /home/ec2-user/Dockerfile
    owner: ec2-user
    group: ec2-user
    mode: 0644

- name: Create Docker Image
  shell: "docker image build -t ultan_lankford/tomcat-pop-hello ./"

- name: Check if container is already running
  shell: "netstat -atunp | grep {{ app_port }} "
  register: result

- name: Run Docker Image as a Container
  shell: "docker container run -d --publish {{ app_port }}:8080 ultan_lankford/tomcat-pop-hello"
  when: result.rc != 1
