---
- name: Enable RHEL extras Repo
  shell: "yum-config-manager --enable rhui-REGION-rhel-server-extras"

- name: Install Docker on EC2 Instance
  package:
    name: docker
    state: present

- name: Enable and Start the docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Copy over built WAR file
  copy:
    src: /home/ec2-user/poppulo/ansible/roles/build_app/files/hello.war
    dest: /home/ec2-user/hello.war
    owner: ec2-user
    group: ec2-user
    mode: 0644

- name: Copy Dockerfile to server
  copy:
    src: /home/ec2-user/poppulo/ansible/roles/install_app/files/Dockerfile
    dest: /home/ec2-user/Dockerfile
    owner: ec2-user
    group: ec2-user
    mode: 0644

#- name: Create Docker Image
#  shell: "docker image build -t ultan_lankford/tomcat-pop-hello ./"

- name: Create Docker Image
  docker_image:
    name: ultan_lankford/tomcat-pop-hello:latest
    build: ./
    source: build

#- name: Run Docker Image as a Container
#  shell: "docker container run -d --publish 80:8080 ultan_lankford/tomcat-pop-hello"

- name: Run Docker Image as a Container
  docker_container:
    name: hello-world-poppulo
    image: utan_lankford/tomcat-pop-hello
    state: started
    detach: yes
    published_ports: 80:8080
