---
- name: Enable RHEL extras Repo
  shell: "yum-config-manager --enable rhui-REGION-rhel-server-extras"

- name: Install Docker on EC2 Instance
  package:
    name: docker
    state: present

- name: Enable and Start the docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Copy over built WAR file
  copy:
    src: /home/ec2-user/poppulo/ansible/roles/build/files/hello.war
    dest: /home/ec2-user/hello.war
    owner: ec2-user
    group: ec2-user
    mode: 0644

- name: Build Docker Image file
  docker_image:
    name: ultan.lankford/poppulo_webapp
    build:
      dockerfile: preset
      path: /home/ec2-user/poppulo/ansible/roles/install_app/files/Dockerfile
      
