---
- name: Create AWS Security Group for Poppulo Webapp
  ec2_group:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    vpc_id: "{{ item.vpcid }}"
    region: "{{ region }}"
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    rules: "{{ item.rules }}"
  with_items: "{{ aws_sg }}"
  register: result

- name: Set group_id fact
  set_fact:
    aws_group_id: "{{ result.results[0].group_id }}"
