---
- name: Create AWS Security Group for Poppulo Webapp
  ec2_group:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    region: "{{ region }}"
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    rules: "{{ item.rules }}"
  with_items: "{{ aws_sg }}" 
