

    - name: These tasks are on the new EC2 instance
      block:
        - name: Enable RHEL extras Repo
          shell: "yum-config-manager --enable rhui-REGION-rhel-server-extras"
          delegate_to: "{{ item.public_ip }}"
          with_items: "{{ result.instances }}"

        - name: Install Docker on EC2 Instance
          package:
            name: docker
            state: present
          delegate_to: "{{ item.public_ip }}"
          with_items: "{{ result.instances }}"

        - name: Enable and Start the docker service
          service:
            name: docker
            state: started
            enabled: yes

        - name: Copy over built WAR file
          copy:
            src: ~/poppulo/ansible/roles/build/files/hello.war
            dest: ~/hello.war
            owner: ec2-user
            group: ec2-user
            mode: 0644
      become: true
